### ISSUE TITLE
Update plugin on sublime packagecontrol.io

### ISSUE THREAD

**Issue by dupriezt** [xsleonard/sublime-MarkdownImages#11]
I downloaded the plugin from sublime's package control (https://packagecontrol.io/packages/Markdown%20Images).
It seems the recent pull-requests that were merged have not made their way there.

**Comment by xsleonard** [comment]
Think I needed to create a release, I've done that now, try it again

**Comment by dupriezt** [comment]
It worked.
![image](https://user-images.githubusercontent.com/32486709/110205383-e863e180-7e77-11eb-98a9-57cf9fbf780b.png)
