### ISSUE TITLE
I can't get the plugin to work

### ISSUE THREAD

**Issue by desbest** [xsleonard/sublime-MarkdownImages#13]
I can't get the plugin to work. I filled in the relevant plugin settings to turn it on and made the syntax highlighting be markdown and still no images appear when I type them in.

**Comment by haferburg** [comment]
I tried it with the "Package Control Messages" text after installing the plugin, which didn't work.

I got it to work with the files in the `qa-test-cases` folder, though.

**Comment by desbest** [comment]
It works now. It looks like v2.1.0 released in October, managed to solve the problem.
