### ISSUE TITLE
set root folder for local images

### ISSUE THREAD

**Issue by arcturus140** [xsleonard/sublime-MarkdownImages#3]
path to local images are relative to sublime project folder. It would be great if this can be changed as per user setting such that images with relative paths are found relative to a custom folder.

**Comment by mef51** [comment]
It seems to me its relative to the folder the file is in no?

**Comment by arcturus140** [comment]
yes you are correct. I would like to place all images in a common folder and in markdown linking to it such that the markdown file can be relocated without changing the link
